[package]
name = "ws-socks5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-tungstenite = "0.18.0"         # Tokio binding for Tungstenite, the Lightweight stream-based WebSocket implementation
tokio = { version = "1.26.0", features = ["full"] }    # An event-driven, non-blocking I/O platform for writing asynchronous I/O backed applications. 
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
